# Generated by Django 4.2.4 on 2023-08-17 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myupdate',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='update_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
